controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

hello:
    path: /hello
    controller: App\Controller\HelloController::index

teste: 
    path: /testeapp
    controller: App\Controller\TesteController::index

second:
    path: /second/{id}
    controller: App\Controller\TesteController::second